version: '3.4'

services:
  chopping.api:
    image: ${DOCKER_REGISTRY-}choppingapi
    build:
      context: .
      dockerfile: Chopping.API/Dockerfile

  shopping.client:
    image: ${DOCKER_REGISTRY-}shoppingclient
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile

  shopping.db:
    image: mongo